(require 'ment "/home/neffr/emacs/ment.el")

(defun whatIsTrue () (list
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; What is true of my experience in general?                              ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; I learned something new. (2 points)
true
;; I achieved something meaningful,
;; or something I can build upon at a later time. (2 points)
true
;; I collaborated with one or more classmates. (2 points)
true

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; What is true of my code's command-line interface?                       ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; It uses *unmodified* the /home/cs238/clear/clearnessCLI.cpp file,
;; which interface handles the case of no command-line arguments, calling
;; a function named *learned*, and then a function named *usage*. (3 points)
true
;; The *learned* function outputs several paragraphs reporting
;; on the learning that happened. (3 points)
true
;; The *usage* function gives instructions on how to run WITH command-line
;; parameters. (3 points)
true

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; What is true of the mechanical "infelicities" (misspelled words,        ;;
;; grammatical errors, punctuation errors) in my report of what I learned? ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; There are fewer than four. (2 points)
true
;; There are fewer than three. (2 points)
true
;; There are fewer than two. (2 points)
true
;; There are none. (2 points)
true

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; What is true about the correctness and completeness of my code          ;;
;; (verified by no "diff" output from the "make just" command)?            ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; It correctly passes Test 1. (4 points)
true
;; It correctly passes Test 2. (4 points)
true
;; It correctly passes Test 3. (4 points)
true
;; It correctly passes Test 4. (4 points)
true
;; It correctly passes Test 5. (4 points)
true
;; It correctly passes Test 6. (4 points)
true
;; It correctly passes Test 7. (4 points)
true
;; It correctly passes Test 8. (4 points)
true
;; It correctly passes Test 9. (5 points)
true

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; What is true about my implementation of the four                        ;;
;; "implement me" functions?                                               ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; *findPrincipal* is implemented in one or two lines of code. (8 points)
true
;; *findMonthlyPayment* is implemented in one or two lines of code. (8 points)
true
;; *findTermInMonths* is implemented in one or two lines of code. (8 points)
true
;; *findPeriodicRate* is implemented in 20 lines of code or fewer
;; using an iterative approach. (8 points)
true
;; *findPeriodicRate* is implemented iteratively but with as few
;; iterations as possible. (8 points)
true
))

;;; Local Variables: 
;;; mode: Emacs-Lisp
;;; compile-command: "whatIsTrue /home/cs238/clear"
;;; TeX-master: t
;;; End: 
