###############################################################################
# Program:
#    Unit 2, Safe String
#    Brother Smithb, CS 470
# Author:
#    Brady Field
# Summary: 
#    Simple driver program to exercise our String class. You may use this
#    driver program or create your own.
#
###############################################################################
a.out: string.h stringTest.cpp
	g++ -o a.out stringTest.cpp
	tar -cf unit2.tar string.h stringTest.cpp makefile